custom/sratoolsncbisettings:
  - modules/nf-core/custom/sratoolsncbisettings/**

fastqc:
  - modules/nf-core/fastqc/**

snakemake:
  - modules/nf-core/snakemake/**

sratools/prefetch:
  - modules/nf-core/sratools/prefetch/**
